### ISSUE TITLE
arrays?

### ISSUE THREAD

**Issue by forgetfulanthropod** [jsdw/angu#14]
hey does it support array literal or object literal syntaxes?
is it possible to write one as a `scope` function?

charlie

P.S. this library is awesome, been building with it for a while

**Comment by forgetfulanthropod** [comment]
hey after going back over stuff I can see it doesn't support them. 
will use "string,of,values" and valuesString.split(',')
🙏

**Comment by jamesandres** [comment]
If it helps someone else, you can create a function (eg: called "array") which reduces its arguments down to an array result which can be used by other operators.

eg:

```javascript
import { evaluate } from 'angu'

const ctx = {
    scope: {
        // NB: Important to use a `function` here and not a fat arrow to use `arguments`
        array: function () {
            return Object.values(arguments).map((arg) => arg.eval());
        },
    }
}

const result = evaluate('array(1, "two", 3)', ctx)
assert.deepStrictEqual(result.value, [1, "two", 3])
```
