### ISSUE TITLE
Custom String Operators

### ISSUE THREAD

**Issue by robokozo** [jsdw/angu#4]
Would it be possible to allow the use of any string as a custom operator?

A cool use case I'd like to explore would be to use this library to write a simple "query" language for some stuff

```
import angu from "angu";
import _ from "lodash";

const releases = [
  {
    id: 1,
    tags: ["a", "b", "c"]
  },
  {
    id: 2,
    tags: ["a", "1"]
  },
  {
    id: 3,
    tags: ["b", "2"]
  },
  {
    id: 4,
    tags: ["c", "3"]
  }
];

const ctx = {
  scope: {
    "&": (a, b) => _.unionWith([...a.eval(), ...b.eval()], x => x.id),
    "|": (a, b) => _.uniqBy([...a.eval(), ...b.eval()], x => x.id),
    "?": (a, b) => releases.filter(r => r[a.eval()].includes(b.eval()))
  },
  precedence: [["?"], ["&"], ["|"]]
};

const resultsA = angu.evaluate("'tags' ? 'a'", ctx);
console.log("A: ", JSON.stringify(resultsA.value));

const resultsBandC = angu.evaluate("'tags' ? 'b' & 'tags' ? 'c'", ctx);
console.log("B AND C's: ", JSON.stringify(resultsBandC.value));

const results1or3 = angu.evaluate("'tags' ? '1' | 'tags' ? '3'", ctx);
console.log("1 OR 3's: ", JSON.stringify(results1or3.value));
```

I'd love to be able to use 
"INCLUDES" instead of "?"
"AND" instead of "&"
"OR" instead of "|"

I can run the strings through a 'variable' replacement step beforehand, but I think it'd be awesome if the library could support this out of the box.

**Comment by jsdw** [comment]
Interesting thought; so far I haven't added support for this sort of thing to avoid potential parsing ambiguities and to keep my options open. You can however use infix functions and so write:

    B `AND` C
    1 `OR` 3

But I acknowledge that that's less nice! I'll have a think about the ramifications of supporting string based operators though, since I think that this is a very valid use case!

**Comment by jsdw** [comment]
This is now possible as of v0.11 (https://github.com/jsdw/angu/commit/82700425d68857a1e1daaf991086bae80ecf78db); As long as the function you want to use infix is explicitly declared in the precedence map, you'll be able to use it now. This can be seen in a few of the examples, for example: https://github.com/jsdw/angu/blob/master/src/examples/jsonFilter.ts
